site_name: DevOps intro 
nav:
- index.md
-  دنیای قبل devops: befor_devops.md
- ظهور devops: devops_evolution.md
- مفاهیم devops: devops_concepts.md
- Containerization: containerization.md
- Orchestration: orchestration.md
- Infrastructure_as_code.md
- version control system: vcs.md
- CI/CD server: CI_CD_server.md
- Monitoring and loging tool: monitoring_tools.md
- cloud computing and DevOps: cloud_computing.md

theme:
  name: material
  language: fa
  direction: rtl

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

watch:
  - ./docs