site_name: DevOps intro 
nav:
  - home: index.md
  - مطالب:
    -  دنیای قبل devops: befor_devops.md
    - ظهور devops: devops_evolution.md
    - مفاهیم devops: devops_concepts.md
    - Containerization: containerization.md
    - Orchestration: orchestration.md
    - Infrastructure_as_code.md
    - version control system: vcs.md
    - CI/CD server: CI_CD_server.md
    - Monitoring and loging tool: monitoring_tools.md
    - cloud computing and DevOps: cloud_computing.md
  - درباره: about.md

theme:
  name: material
  language: fa
  direction: rtl
  logo: assets/logo.svg
  favicon: assets/favicon.svg
  features:
    - navigation.tabs

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

watch:
  - ./docs